### ISSUE TITLE
invoicenumber

### ISSUE THREAD

**Issue by test2a** [Devil7-Softwares/Excel-to-Tally-for-GST#1]
https://github.com/Devil7-Softwares/Excel-to-Tally-for-GST/blob/21d9f1a1116be8256aebd294626e239a385d11fb/E2TGST/Classes/Tally/XMLGenerator.vb#L227

the xml is having issues and i managed to solve the same by exporting  to file, opening the file in notepad and replacing "reference" with "invoicenumber". then imported the same via import/voucher.

**Comment by Devil7DK** [comment]
Could you tell which tally version you are using..?

**Comment by test2a** [comment]
i am using the latest 6.4.9. currently replacing reference with invoicenumber in the xml file works but not without that. Also, because of this, i believe  the direct transfer also doesnt work. Can you compile a version with this change and i have the existing data to check with.

**Comment by Devil7DK** [comment]
> i am using the latest 6.4.9.

Well... I'm also in the same version. Everything working just fine here.

> Can you compile a version with this change and i have the existing data to check with.

Nvm... Implemented an option to choose between "REFERENCE" and "INVOICENUMBER" tags in 
https://github.com/Devil7-Softwares/Excel-to-Tally-for-GST/commit/0f93ad60c9fe535ba96f90cd5983c43e790817a0

This option is disabled by default. You can enable if you want. ~~Will upload new release soon~~. [Uploaded](https://github.com/Devil7-Softwares/Excel-to-Tally-for-GST/releases/tag/v2.2.0)

**Comment by Devil7DK** [comment]
@test2a you can use [e-mail](mailto:devil7softwares@gmail.com) to contact me anytime. plox don't create new "issues" xD
